### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by btzr-io** [Download/i18nline#10] opened 2017-07-19 19:26 UTC
> There is a problem with newlines in your script. Make sure that #!/usr/bin/env node is followed by \n (unix style) instead of \r\n (windows/dos style).
[Node script executable not working](https://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-su./lib/node_modules/i18nline/bin/i18nline.jsch-file-or-directo)

**Comment by btzr-io** [comment] 2017-07-19 19:30
https://github.com/Download/preact-i18nline/issues/6

**Comment by Download** [comment] 2018-03-28 14:37
I understand this issue now and will make sure it gets fixed in the coming weeks. 👍

**Comment by Download** [comment] 2018-04-05 19:58
This should be fixed in v2, along with a boatload of other improvements, including a much leaner project setup (zero-conf FTW!), automatic support for code splitting and hot-reload of translation files, a `synch` command to help managing translation files and best of all, some sane docs that explain how to actually get it all to work. It should be almost fully backward-compatible with v1. You might have to make a small change in your config to enlock the new features.

Hoping you will give v2 a spin and let me know if it works for you. Please feel free to comment here and if the issue is not fixed, please ask for me to re-open it. Thank you for taking the time to file issues!

**Closed by Download** 2018-04-05 19:58 UTC
Labels: bug
